package contants

const (
	// 商城订单状态变更事件
	I_STORE_EVENT_ORDER_STATUS_CHANGE = 0
	// 订单发货事件
	I_STORE_EVENT_ORDER_DETAIL_DELIVERED = 1
	// 订单收货事件
	I_STORE_EVENT_ORDER_DETAIL_RECEIVED = 2
	// 订单创建成功
	I_STORE_EVENT_ORDER_CREATED = 3
	// 取消订单
	I_STORE_EVENT_ORDER_CANCELED = 4
	// 关闭订单
	I_STORE_EVENT_ORDER_CLOSED = 5
	// 订单完成事件
	I_STORE_EVENT_ORDER_COMPLETED = 6
	//卡密商品订单发送卡密信息事件
	I_STORE_EVENT_ORDER_PASSORD_CARD_SEND_MESSAGE = 7
	// 订单自动发货事件
	I_STORE_EVENT_ORDER_DETAIL_AUTO_DELIVERED = 8
	// 订单自动发货失败事件
	I_STORE_EVENT_ORDER_DETAIL_AUTO_DELIVER_FAIL = 9
	// STORE_EVENT_PAYMENT_STATUS_CHANGE 支付状态变更事件
	I_STORE_EVENT_PAYMENT_STATUS_CHANGE = 10
	// 售后退款申请事件
	I_STORE_EVENT_AFTER_SALES_APPLY_REFUND = 11
	// 售后退款审核事件
	I_STORE_EVENT_AFTER_SALES_VERIFY = 12
	// 用户退货完成事件
	I_STORE_EVENT_AFTER_SALES_RETURN = 13
	// 售后退款完成事件
	I_STORE_EVENT_AFTER_SALES_REFUNDED = 14
	// 售后取消事件
	I_STORE_EVENT_AFTER_SALES_CANCEL = 15
	// 售后删除事件
	I_STORE_EVENT_AFTER_SALES_DELETE = 16
	// 售后商品退货收货事件
	I_STORE_EVENT_AFTER_SALES_GOODS_RETURN_RECEIVE = 17
	// 商城配置变更事件
	I_STORE_EVENT_CONFIG_UPDATED = 18
	//用户提现申请完成事件
	I_STORE_EVENT_KICKBACK_EXTRACT = 19
	// 用户注册事件
	I_UCENTER_REGISTERED = 20
	// 用户删除事件
	I_UCENTER_DELETED          = 21
	I_UCENTER_NOTIFICATION_ADD = 22
	// 商品新增事件 -- handler by es
	I_STORE_EVENT_GOODS_ADD = 23
	// 商品删除事件 -- handler by es
	I_STORE_EVENT_GOODS_DELETE = 24
	// 秒杀商品新增事件 -- handler by es
	I_STORE_EVENT_SEC_GOODS_ADD = 25
	// 秒杀商品删除事件 -- handler by es
	I_STORE_EVENT_SEC_GOODS_DELETE = 26
	// web3 新增商品事件
	I_WEB3_STORE_EVENT_GOODS_ADD = 27
	// web3 商品提交上线申请
	I_WEB3_STORE_EVENT_GOODS_LISTING = 28
	// web3 上线审批
	I_WEB3_STORE_EVENT_GOODS_LISTING_APPROVE1 = 29
	I_WEB3_STORE_EVENT_GOODS_LISTING_APPROVE2 = 30
	I_WEB3_STORE_EVENT_GOODS_LISTING_APPROVE3 = 31
	// web3 注册用户(通过推荐码)
	I_WEB3_STORE_EVENT_REGISTER_BY_REFFER_CODE = 32
	// web3 支付
	I_WEB3_STORE_EVENT_PAY_ORDER = 33
)
